### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by HUBBA-ER** [JordanTeamCodingClub/JordanTeamCodingClub.github.io#1]
Is the canvas 400x400?

**Comment by tripplyons** [comment]
No, it is 378x256.

**Comment by HUBBA-ER** [comment]
Thats stupid. Why those obscure numbers?

**Comment by tripplyons** [comment]
256 is 100000000 in binary and 378 is 110000000 in binary. It is good for the computer

**Comment by HUBBA-ER** [comment]
whyyyyyyy oh whyyyyyyyy oh whyyyyyyyyyyyyyyyyyyy
